version: "3"
name: "chatbot"

services:
    mysql:
        container_name: ${APP_NAME}_db
        image: "mysql:8.0.29"
        tty: true
        restart: unless-stopped
        networks:
            - web
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_USER: user
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - ./config/docker/mysql/entrypoint:/docker-entrypoint-initdb.d
            - ./config/docker/mysql/db-data:/var/lib/mysql

    phpmyadmin:
        container_name: ${APP_NAME}_phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8080:80
        networks:
            - web
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=350M
            - PMA_HOST=mariadb

    php-fpm:
        build:
            context: .
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - DB_PROD_HOST
                - DB_PROD_PORT=${DB_PROD_PORT:-3306}
                - SSH_PROD_USER
                - SSH_PROD_SERVER
                - SSH_MYSQL_FORWARD_PORT=${SSH_MYSQL_FORWARD_PORT:-3307}
        container_name: ${APP_NAME}_workspace
        user: "1000:1000"
        restart: unless-stopped
        networks:
            - web
        volumes:
            - ./:/var/www/html
            - ./config/docker/php/php.ini:/usr/local/etc/php/php.ini

    nginx:
        tty: true
        image: nginx:alpine
        container_name: ${APP_NAME}_nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        networks:
            - web
        volumes:
            - ./:/var/www/html
            - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
    web:
        driver: bridge
